// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mapFieldNames          = builder.RawFieldNames(&Map{})
	mapRows                = strings.Join(mapFieldNames, ",")
	mapRowsExpectAutoSet   = strings.Join(stringx.Remove(mapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mapRowsWithPlaceHolder = strings.Join(stringx.Remove(mapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMapIdPrefix   = "cache:map:id:"
	cacheMapMd5Prefix  = "cache:map:md5:"
	cacheMapSurlPrefix = "cache:map:surl:"
)

type (
	mapModel interface {
		Insert(ctx context.Context, data *Map) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Map, error)
		FindOneByMd5(ctx context.Context, md5 sql.NullString) (*Map, error)
		FindOneBySurl(ctx context.Context, surl sql.NullString) (*Map, error)
		Update(ctx context.Context, data *Map) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMapModel struct {
		sqlc.CachedConn
		table string
	}

	Map struct {
		Id        uint64         `db:"id"`
		CreatedAt time.Time      `db:"created_at"`
		CreatedBy string         `db:"created_by"`
		IsDel     uint64         `db:"is_del"`
		Lurl      sql.NullString `db:"lurl"`
		Md5       sql.NullString `db:"md5"`
		Surl      sql.NullString `db:"surl"`
	}
)

func newMapModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMapModel {
	return &defaultMapModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`map`",
	}
}

func (m *defaultMapModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mapIdKey := fmt.Sprintf("%s%v", cacheMapIdPrefix, id)
	mapMd5Key := fmt.Sprintf("%s%v", cacheMapMd5Prefix, data.Md5)
	mapSurlKey := fmt.Sprintf("%s%v", cacheMapSurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mapIdKey, mapMd5Key, mapSurlKey)
	return err
}

func (m *defaultMapModel) FindOne(ctx context.Context, id uint64) (*Map, error) {
	mapIdKey := fmt.Sprintf("%s%v", cacheMapIdPrefix, id)
	var resp Map
	err := m.QueryRowCtx(ctx, &resp, mapIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mapRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMapModel) FindOneByMd5(ctx context.Context, md5 sql.NullString) (*Map, error) {
	mapMd5Key := fmt.Sprintf("%s%v", cacheMapMd5Prefix, md5)
	var resp Map
	err := m.QueryRowIndexCtx(ctx, &resp, mapMd5Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", mapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, md5); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMapModel) FindOneBySurl(ctx context.Context, surl sql.NullString) (*Map, error) {
	mapSurlKey := fmt.Sprintf("%s%v", cacheMapSurlPrefix, surl)
	var resp Map
	err := m.QueryRowIndexCtx(ctx, &resp, mapSurlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `surl` = ? limit 1", mapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, surl); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMapModel) Insert(ctx context.Context, data *Map) (sql.Result, error) {
	mapIdKey := fmt.Sprintf("%s%v", cacheMapIdPrefix, data.Id)
	mapMd5Key := fmt.Sprintf("%s%v", cacheMapMd5Prefix, data.Md5)
	mapSurlKey := fmt.Sprintf("%s%v", cacheMapSurlPrefix, data.Surl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, mapRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreatedBy, data.IsDel, data.Lurl, data.Md5, data.Surl)
	}, mapIdKey, mapMd5Key, mapSurlKey)
	return ret, err
}

func (m *defaultMapModel) Update(ctx context.Context, newData *Map) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mapIdKey := fmt.Sprintf("%s%v", cacheMapIdPrefix, data.Id)
	mapMd5Key := fmt.Sprintf("%s%v", cacheMapMd5Prefix, data.Md5)
	mapSurlKey := fmt.Sprintf("%s%v", cacheMapSurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mapRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreatedBy, newData.IsDel, newData.Lurl, newData.Md5, newData.Surl, newData.Id)
	}, mapIdKey, mapMd5Key, mapSurlKey)
	return err
}

func (m *defaultMapModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMapIdPrefix, primary)
}

func (m *defaultMapModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mapRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMapModel) tableName() string {
	return m.table
}
